FROM node:22-alpine
WORKDIR /app

RUN npm config set strict-ssl false

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps --no-cache

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
