FROM node:22-alpine
WORKDIR /app

RUN npm config set strict-ssl false

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps --no-cache

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
